apiVersion: kaptain.org/1.22
kind: layer-and-layerset-build
metadata:
  description: "GCP GKE cluster management layerset composing quality and build configuration"

spec:
  layers:
    - ghcr.io/kube-kaptain/layerset/layerset-and-layer-build:[1.4,2.0)
  global:
    release:
      versioning:
        maxParts: '3'
        strategy: file-pattern-match
        patternType: custom
        useSourceVersionExact: true
        source:
          subPath: .
          fileName: version.txt
          pattern: '^([0-9]+\.[0-9]+\.[0-9]+)$'
